(function(g){var window=this;var W1=function(a){a.u||(a.u=new g.tn,g.C(a,a.u));return a.u},X1=function(a){a.R("cardstatechange",g.QK(a)&&g.RK(a)?1:0)},soa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Uj&&a.dataset){if(g.ec()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Zc("pollChoiceIndex"))},toa=function(a){return Math.pow(a,3)},uoa=function(a){return 3*a*a-2*a*a*a},Y1=function(a,b){(0,g.z)(b,function(c){c={csn:a,
ve:g.Tr(c),eventType:4};var d={Kj:void 0,Rh:a};"UNDEFINED_CSN"==a?g.ds("visualElementShown",c,d):g.Yq("visualElementShown",c,g.dr,d)})},Z1=function(a,b){(0,g.z)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.Tr(c),eventType:d?16:8};d={Kj:void 0,Rh:a,AD:d};"UNDEFINED_CSN"==a?g.ds("visualElementHidden",c,d):g.Yq("visualElementHidden",c,g.dr,d)})},b2=function(a){a=g.Na(a);
delete $1[a];g.Ub($1)&&a2&&a2.stop()},c2=function(){a2||(a2=new g.J(function(){voa()},20));
var a=a2;a.isActive()||a.start()},voa=function(){var a=(0,g.F)();
g.Hb($1,function(b){d2(b,a)});
g.Ub($1)||c2()},e2=function(a,b,c,d){g.hn.call(this);
if(!g.Ha(a)||!g.Ha(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.M=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},d2=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;f2(a,a.progress);1==a.progress?(a.o=0,b2(a),a.kd(),a.A()):1==a.o&&a.xs()},f2=function(a,b){g.Ja(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.M[c]-a.w[c])*b+a.w[c]},g2=function(a,b){g.ee.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},h2=function(a,b,c,d,e){e2.call(this,b,c,d,e);
this.element=a},i2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
h2.call(this,a,b,c,d,e)},j2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},woa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Nq(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},k2=function(a){return a.baseUrl||null},xoa=function(a,b,c){function d(Ba){var La=Ba.hovercardButton;
if(!La)return null;La=La.subscribeButtonRenderer;if(!La)return null;var fc=f(La.unsubscribedButtonText),dd=f(La.subscribedButtonText);if(La.subscribed){var Dd=f(La.subscriberCountWithUnsubscribeText);var bf=f(La.subscriberCountText)}else Dd=f(La.subscriberCountText),bf=f(La.subscriberCountWithSubscribeText);var fe=null;return Ba.signinEndpoint&&(fe=g.Pb(Ba,"signinEndpoint","webNavigationEndpointData","url"),!fe)?null:fc&&(dd||fe)?{subscribed:La.subscribed,subscribeText:fc,subscribeCount:Dd,unsubscribeText:dd,
unsubscribeCount:bf,enabled:La.enabled,signinUrl:fe,classic:Ba.useClassicSubscribeButton}:null}
function e(Ba){if(Ba){var La=[],fc=Ba.videoId;fc&&La.push("v="+fc);(fc=Ba.playlistId)&&La.push("list="+fc);(Ba=Ba.startTimeSeconds)&&La.push("t="+Ba);return"/watch?"+La.join("&")}}
function f(Ba){if(!Ba)return null;var La=Ba.simpleText;return La?La:Ba.runs?(0,g.xf)(Ba.runs,function(fc){return fc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,v=null,y=null,B=!1,D=null,H=null,G=null,E=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Pb(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?D=d(b):H=f(b.subscribersText)}else"WEBSITE"==
k?((G=g.Pb(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=g.Pb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Pb(b,"title","accessibility","accessibilityData","label");var aa=b.endpoint?b.endpoint.clickTrackingParams:null;return{id:"element-"+c,type:k,title:f(b.title),metadata:b.metadata?f(b.metadata):"",callToAction:f(b.callToAction),Dv:b.image,iconUrl:G,
left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:v,channelId:y,subscribeButton:D,subscribersText:H,isSubscribe:B,targetUrl:m,aF:n,Ib:{itct:aa},QN:q,Aj:a?a:null,eF:b.isPlaceholder,impressionUrls:(0,g.xf)(b.impressionUrls||[],k2),RE:(0,g.xf)(b.hovercardShowUrls||[],k2),clickUrls:(0,g.xf)(l.loggingUrls||[],k2),visualElement:g.Sr(b.trackingParams),productPrice:E,
additionalFeesText:M}},l2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.xf)(a.impressionUrls||[],k2);a.trackingParams&&(c.visualElement=g.Sr(a.trackingParams));var d=(0,g.xf)(a.elements||[],function(e,f){return xoa(b,e,f)});
c.elements=(0,g.Rd)(d,function(e){return!!e});
return c},m2=function(a){g.UO.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.P();this.M=g.Dx(a)||g.Fx(a);this.J=!0;this.G=0;this.B=new g.P(this);g.C(this,this.B);this.B.L(this.player,g.TD("creatorendscreen"),this.MF);this.B.L(this.player,"crx_creatorendscreen",this.NF);this.B.L(this.player,"resize",this.Ix);this.B.L(window,"focus",this.QM);this.load();var b=g.Ld("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.be(this,function(){g.Qd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},n2=function(a){return a.player.getVideoData().kc?"current":a.M?"new":"current"},o2=function(a){return"creator-endscreen-editor"===a.player.P().playerStyle},p2=function(a,b,c){c=void 0===c?!0:c;
g.jQ(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&yoa(a);c=[];d=new g.QD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.P().o||(a.w=new g.V({D:"div",I:"ytp-ce-shadow"}),g.aL(a.player,a.w.element,4),a.C=new g.uL(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=zoa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.aL(a.player,f.element,4);var k=new g.QD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Aoa(a,f,e)}g.XK(a.player,c);
a.Ix()}},yoa=function(a){var b=g.rs(),c=g.ts();
c&&b&&a.u.visualElement&&g.es(c,b,[a.u.visualElement],void 0)},zoa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",W:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.Aj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:q2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:r2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.mn(b.title||"")},V:b.title},{D:"div",I:"ytp-ce-video-duration",V:b.videoDuration}]}]};
c=new g.V(c);break;case "PLAYLIST":c={D:"div",W:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.Aj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:q2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:r2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.mn(b.title||"")},V:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",V:b.playlistLength}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.Aj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",W:["ytp-ce-channel-title","ytp-ce-link"],N:{href:r2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.mn(b.title||"")},V:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",V:b.subscribersText}:"",b.metadata?{D:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
V:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:q2(b)}]};c=new g.V(c);var d=g.wd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.P().o){var e=null;var f=b.Ib.itct}else e="endscreen",f=null;e=new g.zP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",W:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.Aj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",N:{dir:g.mn(b.title||"")},V:b.title},{D:"div",I:"ytp-ce-website-metadata",V:b.metadata},{D:"a",W:["ytp-ce-website-goto","ytp-ce-link"],N:{href:r2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:q2(b)},{D:"div",I:"ytp-ce-expanding-icon",N:s2(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",V:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",V:b.additionalFeesText})),c={D:"div",W:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.Aj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",N:{dir:g.mn(b.title||"")},V:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",V:b.metadata},{D:"a",W:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:r2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:q2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
V:b.callToAction}]}]},c=new g.V(c)}b.eF&&g.K(c.element,"ytp-ce-placeholder");return c},q2=function(a){if(a.Dv)var b=a.Dv.thumbnails;
return s2(b?b[b.length-1].url:null)},s2=function(a){return a?{style:"background-image: url("+a+")"}:{}},Aoa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ga("mouseenter",(0,g.x)(a.vr,a,b,c));b.ga("mouseleave",(0,g.x)(a.Cs,a,b,c));a.player.P().o||b.ga("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ga("click",(0,g.x)(a.oz,a,c));b.ga("keypress",(0,g.x)(a.oz,a,c));b.ga("focus",(0,g.x)(function(l,m){this.vr(l,m)},a,b,c));
b.ga("blur",(0,g.x)(function(l,m){this.Cs(l,m)},a,b,c));
b.ga("touchstart",(0,g.x)(a.vr,a,b,c));var f=g.yd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.fn(b.element,"ytp-ce-element-hover");g.fn(b.element,"ytp-ce-force-expand")});
b.ga("keydown",(0,g.x)(function(l,m){this.J=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),t2(this,m.id,!0)):(g.fn(l.element,"ytp-ce-force-expand"),g.fn(l.element,"ytp-ce-element-hover"),t2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ga("blur",g.Oa(function(){"none"!=m.style.display&&a.J&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.yd("ytp-sb-subscribe",b.element));c(g.yd("ytp-sb-unsubscribe",b.element));b.ga("focus",d);b.ga("blur",e)},r2=function(a,b){var c=a.player.P();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.dy(c)+b}else return"";return b},t2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},u2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||o2(a))c&&c();else{b=Boa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Jp(b[a],d)}},v2=function(a,b,c){u2(a,b.clickUrls,c);
(a=g.ts())&&b.aF&&g.gs(a,b.visualElement)},Boa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Coa(b[e],c));return d},Coa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},w2=function(a){return g.Ha(a)&&a.length?a[0]:a},x2=function(a){return"string"===typeof a?a:""},y2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Eoa=function(a){var b=Doa;
if(null==a)return null;if(g.Ia(a)){var c=[];(0,g.z)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Foa=function(a){this.externalId=a},z2=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},A2=function(a){if(!a)return null;
var b=g.xc(x2(a.value));b=g.vc(b);if(!b)return null;var c=y2(a.target,Goa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new z2(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},B2=function(a){return a.value?a.value:null},C2=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Doa=function(a){if(!a)return null;
var b=y2(a.type,Hoa),c=y2(a.trigger,Ioa),d=w2(a.url);d=A2(d?d:null);a=w2(a.subscribeData);var e=a?a:null;e?(a=x2(e.external_user_id),e=x2(e.subscription_token),a=a&&e?new Foa(a):null):a=null;return b?new C2(b,c,d,a):null},D2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},E2=function(a){return(a=Joa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Joa=function(a,b){return g.Va(a.o,b,void 0)},F2=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Koa=function(a,b){this.merchant=a;
this.price=b},Loa=function(a){this.o=a},Moa=function(a,b,c){b&&(c?G2(a,(0,g.xf)(b,g.Oa(function(d,e){return g.Qm(e,d)},c))):G2(a,b))},G2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.z)(b||[],function(m){e++;
g.Jp(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Noa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.fb=c;this.videoData=d;this.logger=e;this.ca=f;this.u=k},H2=function(a,b){this.o=a;
this.w=b},Poa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(Ooa(b,k))},a);
var d={D:"ul",N:{role:"radiogroup"},K:c},e={};b.Vh&&(e["aria-label"]=g.bM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[I2("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Vh&&(f.push("iv-card-unavailable"),d.push({D:"div",W:["iv-card-sign-in"],K:[{D:"h2",V:"Want to vote?"},{D:"a",W:["iv-card-sign-in-button","iv-button"],N:{href:B2(b.Vh)},K:[{D:"span",W:["iv-button-content"],V:"Sign in"}]}]}));f=new g.V({D:"div",
W:f,K:d});d=f.element;J2(b,d);woa(a.o.o,d,g.Oa(a.A,b),a);(0,g.z)(g.xd("iv-card-poll-choice-input",d),function(k){this.o.o.ga(k,"focus",g.Oa(this.u,!0));this.o.o.ga(k,"blur",g.Oa(this.u,!1))},a);
b.Vh&&(d=g.yd("iv-card-sign-in-button",d),a.w(d,b.Vh,b.id,b.Ib,b.Bc.click,5));return f},N2=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.jO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.dF&&b.Xu?{D:"span",W:d,N:e,V:b.Xu}:"";c={D:"div",W:["iv-card",c],K:[{D:"a",I:"iv-click-target",N:{href:B2(b.url)},K:[K2(b.Yh,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",V:b.title},L2(a,b)]}]}]};c=new g.V(c);M2(a,g.xd("iv-click-target",c.element),b,b.url);return c},O2=function(a){return a.customMessage?
I2("div","iv-card-message",a.customMessage):""},K2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",N:{style:c},K:d}},L2=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(I2("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Ooa=function(a,b){return{D:"li",
I:F2(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},I2("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},I2=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ha(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.mn(c);return{D:a,N:b,V:c}},P2=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.gm&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.gm+");");c.dir=g.mn(a.customMessage);var d=[{D:"span",V:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",W:b,N:c,K:d}},J2=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.yd(F2(a,e.index),b);e=e.count/c;null==a.oe&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.oe==d);f.getElementsByTagName("input")[0].checked=a.oe==d;var k=Math.floor(100*e).toFixed(0),l=g.yd("iv-card-poll-choice-percent",f);g.Vd(l,g.bM("$PERCENT%",{PERCENT:k}));f=g.yd("iv-card-poll-result-bar",f);g.hh(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.oe);g.L(b,"iv-card-poll-expanded",
null!=a.oe&&1<a.choices.length)},M2=function(a,b,c,d){d&&(0,g.z)(b,function(e){this.w(e,d,c.id,c.Ib,c.Bc.click,5)},a)},Q2=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Qoa=function(a,b){return b?b:Q2(a)?"current":"new"},R2=function(a,b){g.A.call(this);
this.o=a;this.context=b;this.Pt=!1},Roa=function(a,b,c,d,e){var f=B2(b);
if(f){var k=Qoa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ca.pauseVideo();var m=this.context.videoData.kc||!1,n=g.Wo(f||"");m&&n&&(n.v||n.list)?g.IS(this.context.ca.app,n.v,c,n.list,!1,void 0):g.fM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);G2(a.context.logger,d,l,e);Q2(f)||(a=g.ts(),d=c.itct,a&&d&&g.gs(a,g.Sr(d)))}},S2=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},T2=function(a,b,c){return{Pw:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
eB:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Co:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},W2=function(a,b,c){R2.call(this,b,c);
var d=this;this.w=a;this.da=this.Aa=this.C=this.za=!1;this.na=null;this.Y=new g.J(g.Ea,c.fb.Qa?4E3:3E3);g.C(this,this.Y);this.sa=new g.J(g.Ea);g.C(this,this.sa);this.H=new H2(c,(0,g.x)(this.lj,this),(0,g.x)(this.jn,this));this.U=new g.V({D:"div",I:"iv-drawer",N:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",W:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.C(this,this.U);this.F=this.U.element;this.ia=new g.uL(this.U,330);g.C(this,this.ia);this.ya=g.yd("iv-drawer-header-text",this.F);this.B=g.yd("iv-drawer-content",this.F);this.A=[];this.xa=this.S=this.G=this.ea=this.u=null;this.Z=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Aa&&U2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Aa=d.C)&&V2(d)});
this.O=this.M=this.aa=null;this.J=0},Soa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){U2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){V2(a)});
var c=b.data.headerText;g.Vd(a.ya,c);a.S&&a.S.setAttribute("title",c);a.aa=g.Sr(b.data.trackingParams);a.O=g.Sr(b.data.closeTrackingParams);a.M=g.Sr(b.data.iconTrackingParams)},Toa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"simple",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ib:X2(a,c,b,d),sponsored:!1,Bc:T2(d,e,d.command),Qd:d.trackingParams?g.Sr(d.trackingParams):null,Hd:e.trackingParams?
g.Sr(e.trackingParams):null,bd:f&&f.trackingParams?g.Sr(f.trackingParams):null,imageUrl:Y2(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.gA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,gm:null,title:d.title?g.gA(d.title):"",customMessage:d.callToAction?g.gA(d.callToAction):"",url:d.command.urlEndpoint.url?A2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};Z2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"collaborator",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ib:X2(a,c,b,d),sponsored:!1,Bc:T2(d,e,d.endpoint),Qd:d.trackingParams?g.Sr(d.trackingParams):null,Hd:e.trackingParams?g.Sr(e.trackingParams):null,bd:f&&f.trackingParams?
g.Sr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.gA(d.customText):null,bA:Y2(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.gA(d.channelName):"",metaInfo:[d.subscriberCountText?g.gA(d.subscriberCountText):""],url:A2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};Z2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"playlist",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ib:X2(a,c,b,d),sponsored:!1,Bc:T2(d,e,d.action),Qd:d.trackingParams?g.Sr(d.trackingParams):null,Hd:e.trackingParams?g.Sr(e.trackingParams):null,bd:f&&f.trackingParams?g.Sr(f.trackingParams):
null,Yh:Y2(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.gA(d.customMessage):null,playlistVideoCount:g.gA(d.playlistVideoCount),title:d.playlistTitle?g.gA(d.playlistTitle):"",metaInfo:[d.channelName?g.gA(d.channelName):"",d.videoCountText?g.gA(d.videoCountText):""],url:A2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:S2(d.action)})};Z2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"video",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ib:X2(a,c,b,d),sponsored:!1,Bc:T2(d,e,d.action),Qd:d.trackingParams?g.Sr(d.trackingParams):null,Hd:e.trackingParams?g.Sr(e.trackingParams):null,bd:f&&f.trackingParams?g.Sr(f.trackingParams):null,Yh:Y2(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.gA(d.lengthString):null,customMessage:d.customMessage?g.gA(d.customMessage):null,title:d.videoTitle?g.gA(d.videoTitle):"",metaInfo:[d.channelName?g.gA(d.channelName):"",d.viewCountText?g.gA(d.viewCountText):""],isLiveNow:!!d.badge,url:A2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:S2(d.action)})};Z2(a,c)}a.J++},Y2=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},X2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},a3=function(a,b){var c=Uoa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Qd(c.zp),g.bb(a.A,c),a.im(),$2(a))},U2=function(a,b,c){if(!a.C){a.ia.show();
a.ea=new g.J(function(){g.K(g.HK(a.context.ca),"ytp-iv-drawer-open")},0);
a.ea.start();a.na=g.Eq(a.B,"mousewheel",(0,g.x)(a.jG,a));a.C=!0;var d=g.ts();d&&a.aa&&a.O&&Y1(d,[a.aa,a.O]);var e={TRIGGER_TYPE:b};(0,g.z)(a.A,function(f){f.tx||(f.tx=!0,Moa(a.context.logger,f.card.Bc.Pw,e));d&&Y1(d,[f.card.Qd])});
X1(a.w);c&&(a.G=new g.J(function(){a.oa=a.S;a.xa.focus()},330),a.G.start())}},V2=function(a){a.C&&(a.ia.hide(),g.Fq(a.na),a.na=null,g.fn(g.HK(a.context.ca),"ytp-iv-drawer-open"),a.C=!1,X1(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.oa&&(a.oa.focus(),a.oa=null)},330),a.G.start())},Voa=function(a){var b=g.yd("iv-drawer-close-button",a.F);
a.context.o.ga(b,"click",a.jD,a);a.context.o.ga(a.B,"touchend",function(){a.Y.start()});
a.context.o.ga(a.B,"scroll",a.xD,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.dn(g.HK(a.w),"ytp-autohide")});
a.Z.push(g.wo("iv-button-shown",a.oF,a));a.Z.push(g.wo("iv-button-hidden",a.nF,a));a.Z.push(g.wo("iv-teaser-shown",a.rF,a));a.Z.push(g.wo("iv-teaser-hidden",a.qF,a));a.Z.push(g.wo("iv-teaser-clicked",a.pF,a))},Z2=function(a,b){a.za||(g.en(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.aL(a.w,a.F,5),Voa(a),a.S=g.yd("ytp-cards-button",g.HK(a.w)),a.xa=g.yd("iv-drawer-close-button",a.F),a.za=!0);a3(a,b.id);var c=Woa(a,b);if(c){var d={card:b,zp:c.element,tx:!1},e=Xoa(a,d);g.ib(a.A,e,0,d);c.ba(a.B,e);a.im();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Oa(a.CN,d)):(c=1E3*a.context.ca.getCurrentTime(),5E3>c&&c>b.startMs&&a.IA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Oa(a.IA,d)),$2(a))}},Woa=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",V:b.displayDomain}:"";var e=P2(b);d={D:"div",W:["iv-card"],K:[{D:"a",I:"iv-click-target",N:{href:B2(b.url)},K:[K2(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[I2("h2",void 0,b.title),e]}]}]};d=new g.V(d);M2(c,g.xd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",W:["iv-card","iv-card-channel"],K:[{D:"a",W:["iv-click-target"],N:{href:B2(b.url),"data-ytid":b.channelId},K:[K2(b.bA),{D:"div",I:"iv-card-content",
K:[O2(b),{D:"h2",I:"iv-card-primary-link",V:b.title},L2(c,b)]}]}]},d=new g.V(d),M2(c,g.xd("iv-click-target",d.element),b,b.url),d;case "episode":return N2(a.H,b,"iv-card-episode");case "movie":return N2(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",W:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",N:{href:B2(b.url)},K:[K2(b.Yh,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",V:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[O2(b),
I2("h2","iv-card-primary-link",b.title),L2(c,b)]}]}]},d=new g.V(d),M2(c,g.xd("iv-click-target",d.element),b,b.url),d;case "poll":return Poa(a.H,b);case "productListing":c=a.H;var f=!g.Za(b.offers);d=["iv-card"];e="";var k=P2(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",V:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",V:f.merchant}),k={D:"div",K:k});d={D:"div",W:d,N:{tabindex:"0"},K:[{D:"a",W:["iv-card-image",
"iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:B2(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",V:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",N:{href:B2(b.url)},K:[I2("h2",e,b.title),k]}]}]};d=new g.V(d);e=g.Ld("span");
g.Vd(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.qb(e,"adInfo");M2(c,g.xd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",W:["yt-badge","yt-badge-live"],V:"LIVE NOW"}:"",d={D:"div",W:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",N:{href:B2(b.url)},K:[K2(b.Yh,b.videoDuration?{D:"span",I:"iv-card-video-duration",V:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[O2(b),I2("h2","iv-card-primary-link",b.title),L2(c,b),d]}]}]},d=new g.V(d),M2(c,g.xd("iv-click-target",d.element),b,b.url),d}return null},Xoa=function(a,b){if(0==a.A.length)return 0;
var c=g.Wa(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Yoa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.ii)(a.A,function(b){return"productListing"==b.card.type})},$2=function(a){g.L(g.HK(a.w),"ytp-cards-shopping-active",Yoa(a))},b3=function(a,b){if(a.U.Ia()){var c=new e2([0,
a.B.scrollTop],[0,b.zp.offsetTop],600,uoa);a.context.w.ga(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ga(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.DC(a.U,!0),a.B.scrollTop=b.zp.offsetTop,g.DC(a.U,!1)},c3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Uoa=function(a,b){return g.Va(a.A,function(c){return c.card.id==b})},d3=function(a,b,c){R2.call(this,a,b);
this.annotation=c;this.isActive=!1},Zoa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},e3=function(a,b,c){d3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},f3=function(a,b,c){d3.call(this,a,b,c);
this.M=this.C=this.J=!1;this.G=5E3;this.B=null;this.H=g.Kd("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.Bh(this.A,!1);g.Bh(this.w,!0)},700,this);
g.C(this,this.F)},$oa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=E2(a.annotation),f=b.image_url;if(f){var k=g.Kd("DIV",["iv-promo-img","iv-click-target"]);f=g.Kd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Kd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Kd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.lj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Kd("A","iv-promo-txt"),g.Oc(f,B2(e)),a.u=f):a.u=g.Kd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Kd("P",null,g.Kd("STRONG",null,b.text_line_1));var m=g.Kd("P",null,g.Kd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.fb.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Kd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Kd("BUTTON",["iv-button","iv-promo-button"],g.Kd("SPAN","iv-button-content",f));var q=g.Kd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.lj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.lj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Kd("P",null,g.Kd("SPAN",null,b.text_line_1)),
m=g.Kd("P",null,g.Kd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Kd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.lj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Kd("DIV","iv-promo-actions");a.w=g.Kd("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ga(a.w,"click",g.Oa(a.tq,5E3),a);c.appendChild(a.w);g.Bh(a.w,!1);
a.context.o.ga(a.o,"mouseover",a.uE,a);a.context.o.ga(a.o,"mouseout",a.tE,a);a.context.o.ga(a.o,"touchend",g.Oa(a.tq,5E3),a);a.A=g.Kd("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ga(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.nE:a.mE,a);c.appendChild(a.A);g.en(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},g3=function(a){a.C||a.M||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},h3=function(a){a.F.stop();
a.C&&(g.gn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Bh(a.w,!1),g.Bh(a.A,!0))},j3=function(a,b){a.B||(a.B=g.qf(function(){i3(this);
g3(this)},b,a))},i3=function(a){a.B&&(g.u.clearTimeout(a.B),a.B=null)},k3=function(a){g.UO.call(this,a);
this.M=!1;this.H=0;this.F={};this.U=new Loa(a);this.B=new g.P(this);g.C(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.qL,this);this.subscribe("resize",this.ao,this);this.player.P().F.subscribe("vast_info_card_add",this.Pz,this);this.S=new g.P(this);g.C(this,this.S);this.O=g.Kd("DIV","video-custom-annotations");this.u=new g.V({D:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.aL(this.player,this.u.element,4);this.u.hide();this.A=new g.V({D:"div",W:["ytp-iv-video-content"]});g.C(this,this.A);g.Nd(this.A.element,g.Kd("DIV","video-annotations",
this.O));this.G=this.o=null;this.J=[];apa(this)&&this.load();var b=g.Ld("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.be(this,function(){g.Qd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},l3=function(){var a=g.Kd("DIV",["annotation",
"annotation-type-custom"]);g.Bh(a,!1);return a},m3=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},apa=function(a){var b=a.player.P();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.JB||null!==b.F.get(a.videoId)},n3=function(a,b,c){a.M=!0;
a.C=g.pp(b,c)},o3=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ka(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(o3(a,e))}return c},p3=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},bpa=function(a){var b=a.player.getVideoData();
if(b.Pd){var c=a.player.P().F.get(b.videoId);if(c){var d={format:"XML",Kd:{},method:"POST",withCredentials:!0};d.kd=(0,g.x)(function(e,f,k){p3(this,e,f)||(e=g.jp(k)&&k.responseXML?k.responseXML:null)&&q3(this,e)},a,a.H,b.videoId);
g.Lo()&&(d.kd=r3(a,d.kd));d.wb={ic_only:"1"};s3(d,c);a.M=!0;g.pp(b.Pd,d)}}},s3=function(a,b){a.method="POST";
a.wb=a.wb||{};b.mm&&(a.wb.ic_coll=b.mm);b.nm&&(a.wb.ic_xml=b.nm);b.Al&&(a.wb.ic_track=b.Al)},u3=function(a){var b=new g.V({D:"div"});
g.Bh(b.element,!1);var c=new W2(a.player,b.element,t3(a));g.C(c,b);b.ba(a.u.element);c.ol();return c},t3=function(a){if(!a.G){var b=new j2(a);
g.C(a,b);var c=new g.v0(a);g.C(a,c);a.G=new Noa(b,c,a.player.P(),a.player.getVideoData(),a.U,a.player,a.Yb)}return a.G},q3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ts();if(e){var f=g.rs();f&&g.es(e,f,[g.Sr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=o3(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=y2(k.type,cpa),t=y2(k.style,dpa),v=x2(k.data),y=0!=v.length?JSON.parse(v):{},B=Eoa(k.action);f=n&&q?new D2(n,q,t,B,y):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=l3(),H=null;switch(m.type){case "branding":if(k.player.P().Pa)break;k.u.element.appendChild(D);H=new e3(D,t3(k),m);break;case "promotion":g.aL(k.player,D,4),H=new f3(D,t3(k),m)}H&&H.ol();if(k=H)g.C(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=u3(a),g.C(a,a.o));if("card"==f.type){if(c=a.o,H=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Pw:k.impression,click:k.click,close:k.close,eB:k.teaser_impression,Co:k.teaser_click},m=f.data.tracking_params||
{},D=null,H){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):null,bd:m.icon?g.Sr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,bA:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:A2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};Z2(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):null,bd:m.icon?g.Sr(m.icon):
null,Yh:f.data.image_url,Xu:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,dF:!!f.data.is_paygated,jO:!!f.data.user_has_entitlement,url:A2({target:f.data.target||"new",value:f.data.url})};Z2(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||
!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):null,bd:m.icon?g.Sr(m.icon):null,Yh:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:A2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};Z2(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):null,bd:m.icon?g.Sr(m.icon):null,title:f.data.title,choices:f.data.choices,oe:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Vh:f.data.signin_url?A2({target:"current",value:f.data.signin_url}):null,uO:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};Z2(c,f);break;case "productListing":f.data.signin_url&&(D=A2({target:"current",
value:f.data.signin_url}));H=[];for(var G=f.data.offers||[],E=0;E<G.length;E++)H.push(new Koa(g.Vc(G[E].merchant),g.Vc(G[E].price)));f={BS:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):null,bd:m.icon?g.Sr(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,gm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:A2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Vh:D,NS:f.data.signin_title?f.data.signin_title:null,MS:f.data.signin_message?f.data.signin_message:null,offers:H};Z2(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):null,bd:m.icon?g.Sr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,gm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:A2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};Z2(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ib:f.data.session_data||{},sponsored:f.data.sponsored||!1,Bc:k,Qd:m.card?g.Sr(m.card):null,Hd:m.teaser?g.Sr(m.teaser):
null,bd:m.icon?g.Sr(m.icon):null,Yh:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:A2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},Z2(c,f)}}else Soa(a.o,f);c=!0}}}c&&(X1(a.player),a.ao())},epa=function(a,b){var c=!1;
a.o||(a.o=u3(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Toa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.gA(b.headerText):"",g.Vd(c.ya,d),c.S&&c.S.setAttribute("title",d),c.aa=b.trackingParams?g.Sr(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.Sr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.M=b.icon.infoCardIconRenderer.trackingParams?g.Sr(b.icon.infoCardIconRenderer.trackingParams):null,X1(a.player),a.ao())},
fpa=function(a,b,c,d,e){if(!a.player.P().Pa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new C2("openUrl","click",new z2("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.gA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.gA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.gA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.gA(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.gA(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.gA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new D2(c,"branding","branding",f,d);d=l3();a.u.element.appendChild(d);f=new e3(d,t3(a),f);f.ol();g.C(f,f);a.F[c]=f}},r3=function(a,b){return(0,g.x)(function(){if(!this.ka()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Oa.apply(window,c);this.J.push(g.Jo(b))}},a)},$1={},a2=null;g.Qa(e2,g.hn);g.h=e2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;b2(this);this.startTime=a=(0,g.F)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.ge("play");-1==this.o&&this.ge("resume");this.o=1;var b=g.Na(this);b in $1||($1[b]=this);c2();d2(this,a);return!0};
g.h.stop=function(a){b2(this);this.o=0;a&&(this.progress=1);f2(this,this.progress);this.ge("stop");this.A()};
g.h.pause=function(){1==this.o&&(b2(this),this.o=-1,this.ge("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.ge("destroy");e2.Bb.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.xs=function(){this.ge("animate")};
g.h.ge=function(a){this.dispatchEvent(new g2(a,this))};
g.Qa(g2,g.ee);g.Qa(h2,e2);h2.prototype.C=g.Ea;h2.prototype.xs=function(){this.C();h2.Bb.xs.call(this)};
h2.prototype.A=function(){this.C();h2.Bb.A.call(this)};
h2.prototype.B=function(){this.C();h2.Bb.B.call(this)};
g.Qa(i2,h2);i2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(j2,g.A);j2.prototype.ga=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Eq(a,b,c);this.o.push(a);return a};
j2.prototype.er=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Oq(a,b,c);this.o.push(a);return a};
j2.prototype.Va=function(a){g.Fq(a);g.bb(this.o,a)};
j2.prototype.X=function(){g.Fq(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.r(m2,g.UO);g.h=m2.prototype;g.h.load=function(){g.UO.prototype.load.call(this);if(!o2(this)){var a=g.MB(this.player.getVideoData());if(a)a=l2(a,n2(this)),p2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",kd:(0,g.x)(this.cK,this,a),Kd:{v:a},withCredentials:!0};this.M&&(a.Kd.ptype="embedded");var c=this.player.getVideoData().zm;c&&(a.wb={ad_tracking:c});if(b=g.LB(b))if(b=g.xc(b),b=g.vc(b))this.A=g.pp(b,a)}}};
g.h.unload=function(){p2(this,null);this.A&&(this.A.abort(),this.A=null);g.UO.prototype.unload.call(this)};
g.h.Hc=function(a,b){if(!o2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=l2(b,"new");p2(this,c);return!0}return null};
g.h.getOptions=function(){return o2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.cK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=l2(c,n2(this)))}p2(this,c)};
g.h.Ix=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<v3.length;f++){var k=Math.abs(b.width-v3[f]);if(-1==e||d>=k)e=f,d=k}d=w3[e];this.w&&g.hh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.zh(e.element,Math.round(k.width*a.width),f);g.ph(e.element,m,n);g.gn(e.element,gpa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.gn(e.element,w3);g.K(e.element,d);(e=g.wd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.hh(e,"height",f+"px")}}}}};
g.h.MF=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())u2(this,this.u.impressionUrls),(a=g.ts())&&this.u.visualElement&&g.fs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.K(g.HK(this.player),"ytp-ce-shown");u2(this,c.impressionUrls);(b=g.ts())&&g.fs(b,c.visualElement);this.player.P().Ab&&this.player.la("endscreenelementshown",a)}};
g.h.NF=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.fn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.fn(g.HK(this.player),"ytp-ce-shown");this.player.P().Ab&&this.player.la("endscreenelementhidden",a)}};
g.h.QM=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.gn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.oz=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.dn(c,"ytp-ce-element");){g.dn(c,"subscribe-label")&&v2(this,a);if(g.dn(c,"ytp-ce-channel-subscribe"))return;c=g.Td(c)}if(!c||g.dn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Cs(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.QN?(v2(this,a),this.HA(),this.player.pauseVideo(),c=g.xc(r2(this,a.targetUrl)),c=g.vc(c),g.fM(c,void 0,a.Ib)):(c=this.player.getVideoData().kc,
c=(0,g.x)(this.KN,this,c,r2(this,a.targetUrl),a.Ib),c=(0,g.x)(this.HA,this,c),v2(this,a,c))}}};
g.h.KN=function(a,b,c){var d=g.Wo(b);a&&d&&(d.v||d.list)?g.IS(this.player.app,d.v,c,d.list,!1,void 0):g.eM(b,c)};
g.h.vr=function(a,b){g.dn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.P().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),u2(this,b.RE),t2(this,b.id,!0))};
g.h.Cs=function(a,b){g.fn(a.element,"ytp-ce-element-hover");g.fn(a.element,"ytp-ce-force-expand");t2(this,b.id,!1)};
g.h.HA=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var v3=[346,426,470,506,570,640,853,1280,1920],w3="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),gpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Goa={zP:"current",VQ:"new"};var Hoa={CLOSE:"close",YQ:"openUrl",EC:"subscribe"},Ioa={tP:"click",CLOSE:"close",kQ:"hidden",DR:"rollOut",ER:"rollOver",HR:"shown"};var dpa={WO:"anchored",ZB:"branding",CHANNEL:"channel",yP:"cta",mQ:"highlightText",EQ:"label",PLAYLIST:"playlist",qR:"popup",LR:"speech",EC:"subscribe",VR:"title",VIDEO:"video",iS:"website"},cpa={ZB:"branding",kP:"card",FP:"drawer",lQ:"highlight",LQ:"marker",vR:"promotion",TEXT:"text",kS:"widget"};H2.prototype.u=function(a,b){var c=g.$d(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
H2.prototype.A=function(a,b){var c=g.$d(b.target,null,"iv-card-poll",void 0);if(c)if(a.Vh)g.yd("iv-card-sign-in-button",c).click();else{var d=parseInt(soa(b.target),10);if(null==a.oe)a.choices[d].count++,a.oe=d;else if(a.oe!=d){var e=a.choices[a.oe];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.oe=d}else e=a.choices[a.oe],e.count=Math.max(e.count-1,0),a.oe=null;J2(a,c);g.tp(this.o.videoData.Pd,{Kd:{action_poll_vote:1},wb:{poll_id:a.id,index:d,session_token:a.uO}});G2(this.o.logger,a.Bc.click,
void 0,5);(c=g.ts())&&a.Qd&&g.gs(c,a.Qd)}};g.r(R2,g.A);g.h=R2.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.QD(a,b,{id:c});g.C(this,a);a.namespace="annotations_module";d&&W1(a).subscribe("onEnter",d,this);e&&W1(a).subscribe("onExit",e,this);g.XK(this.context.ca,[a])};
g.h.ol=function(){this.context.u.subscribe("resize",this.im,this)};
g.h.lj=function(a,b,c,d,e,f){this.context.o.ga(a,"click",g.Oa(this.jn,b,c,d,e||[],f||0),this);this.context.o.ga(a,"touchstart",g.Oa(function(){this.Pt=!1}),this);
this.context.o.ga(a,"touchmove",g.Oa(function(){this.Pt=!0}),this)};
g.h.jn=function(a,b,c,d,e,f){if(this.Pt)return!1;f&&(f.stopPropagation(),f.preventDefault());Roa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Qd(this.o)};
g.h.im=function(){};g.r(W2,R2);g.h=W2.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.HK(this.w))?(a=g.Ah(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.im=function(){var a=this.isAvailable();g.Bh(this.o,a);g.L(g.HK(this.context.ca),"ytp-iv-drawer-enabled",a);X1(this.w)};
g.h.destroy=function(){var a=g.PK(g.CK(this.w));a&&a.ur(!1,void 0);try{g.HK(this.w).removeChild(this.F)}catch(b){}g.xo(this.Z);g.Fq(this.na);this.ea&&this.ea.dispose();this.G&&this.G.dispose();R2.prototype.destroy.call(this)};
g.h.jG=function(a){this.Y.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.IA=function(a){if(!g.dn(g.HK(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.ts(),c=this.u?this.u.card.bd:this.M;b&&c&&Z1(b,[c]);this.u=a;$2(this)}if(b="none"!=this.o.style.display)2==this.context.ca.getPresentingPlayerType()?b=1==this.context.ca.getAdState():(b=this.context.ca.getPlayerState(),c=0==b&&0===this.context.ca.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.PK(g.CK(this.w)))&&c.ur(!0,b));
this.sa.isActive()||((!this.C||!this.Y.isActive()&&this.da)&&b3(this,a),this.sa.start(910+a.card.teaserDurationMs))}};
g.h.CN=function(a){this.C||(this.u=a,$2(this),b3(this,a),U2(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.jD=function(){if(this.C){G2(this.context.logger,c3(this).Bc.close);var a=g.ts();a&&this.O&&g.gs(a,this.O);V2(this)}};
g.h.xD=function(){g.L(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.oF=function(){var a=g.ts(),b=c3(this);b=b?b.bd:this.M;a&&b&&Y1(a,[b])};
g.h.nF=function(){var a=g.ts(),b=c3(this);b=b?b.bd:this.M;a&&b&&Z1(a,[b])};
g.h.rF=function(){var a=c3(this);G2(this.context.logger,a.Bc.eB);var b=g.ts();b&&a&&Y1(b,[a.Hd,a.bd])};
g.h.qF=function(){var a=g.ts(),b=c3(this);a&&b&&Z1(a,[b.Hd])};
g.h.pF=function(a){var b=c3(this),c=g.ts();this.u?a?(a=this.context.logger,G2(a,b.Bc.Co),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Hd&&g.gs(c,b.Hd)):(a=this.context.logger,G2(a,b.Bc.Co),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.bd&&g.gs(c,b.bd)):(a=this.context.logger,G2(a,b.Bc.Co),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.M&&g.gs(c,this.M))};g.r(d3,R2);d3.prototype.ol=function(){R2.prototype.ol.call(this);Zoa(this)};
d3.prototype.show=function(){R2.prototype.show.call(this);var a=g.ts(),b=this.annotation.data;a&&b&&(b=b.session_data)&&Y1(a,[g.Sr(b.itct)])};
d3.prototype.hide=function(){R2.prototype.hide.call(this);var a=g.ts(),b=this.annotation.data;a&&b&&(b=b.session_data)&&Z1(a,[g.Sr(b.itct)])};g.r(e3,d3);g.h=e3.prototype;g.h.LN=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Ah(a);this.u||(g.yh(a,e.width),g.yh(b,e.width));g.hh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.hh(c,"right","1px");this.B=!0;g.Bh(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.QE=function(a,b){g.fn(this.o,"iv-branding-active");this.F=new g.J((0,g.x)(function(){g.Bh(a,!1);this.u||g.yh(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){d3.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Kd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Bh(this.w,!1);var b=g.Kd("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=E2(this.annotation))&&this.lj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Kd("DIV","iv-branding-context-name");
g.Vd(c,a.channel_name);var d=g.Kd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.zP(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ca),this.u.ba(d);b=g.Kd("DIV","iv-branding-context-subscribe-caret");c=g.Kd("DIV","branding-context-container-inner",b,c,d);g.Bh(c,!1);d=g.Kd("DIV","branding-context-container-outer",c);g.hh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Oa(this.QE,c,d),500,this);g.C(this,this.A);this.context.o.ga(this.o,"mouseover",(0,g.x)(this.LN,this,c,d,b,a.image_height));this.context.o.ga(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Bh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.th(a);c=g.Ah(a);b=(new g.eh(b.x,b.y,c.width,c.height)).width;g.ph(a,b);e=new i2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,toa);g.C(this,e);this.context.w.ga(e,
"begin",g.Oa(g.Bh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(d3.prototype.hide.call(this),g.Bh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);d3.prototype.destroy.call(this)};g.r(f3,d3);g.h=f3.prototype;g.h.show=function(){this.isActive||(d3.prototype.show.call(this),this.J||($oa(this),this.J=!0),g.Bh(this.o,!0),g.qf(function(){g.fn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,i3(this),h3(this),j3(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.jn=function(a,b,c,d,e,f){return this.C?!1:d3.prototype.jn.call(this,a,b,c,d,e,f)};
g.h.tq=function(a,b){b.stopPropagation();h3(this);j3(this,a);this.u.focus()};
g.h.uE=function(a){this.M=!0;this.tq(500,a)};
g.h.tE=function(){this.M=!1;g3(this)};
g.h.mE=function(a){a.stopPropagation();this.hide()};
g.h.nE=function(a){a.stopPropagation();i3(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();d3.prototype.destroy.call(this)};g.r(k3,g.UO);g.h=k3.prototype;g.h.Hc=function(a,b){if(!m3(this.player.P().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.u0(b);c&&q3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(a3(this.o,b),X1(this.player)),!0}return null};
g.h.getOptions=function(){return m3(this.player.P().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.ao=function(){if(this.A){var a=g.GK(this.player).getVideoContentRect(!0);g.zh(this.A.element,a.width,a.height);g.ph(this.A.element,a.left,a.top)}if(this.o){var b=g.SK(this.player);a=this.o;b=b.width;g.L(a.F,"iv-drawer-small",426>=b);g.L(a.F,"iv-drawer-big",1280<=b)}};
g.h.qL=function(a){this.dc(a.state);g.W(a.state,2)&&(this.Ck()&&this.Gx()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ur(!1))};
g.h.load=function(){g.UO.prototype.load.call(this);this.dc(g.JK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.eK,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Lo()&&(c=r3(this,c));c={format:"XML",kd:c,onError:d,Kd:{}};a.isPharma&&(c.Kd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.P().F.get(b))&&s3(c,b);b=b&&(b.nm||b.mm);if(!a.Yl||b)a.Pd?n3(this,a.Pd,c):(this.w=(0,g.x)(this.KF,this,c),this.player.addEventListener("videodatachange",this.w));g.aL(this.player,this.A.element,4);this.ao();(b=a.Ja&&a.Ja.cards&&a.Ja.cards.cardCollectionRenderer||null)&&epa(this,b);(b=g.NB(a))&&b.featuredChannel&&fpa(this,b.featuredChannel,b.annotationId||"branding",
a.videoId||null,a.eventId||null)};
g.h.dc=function(a){a=!a.isCued()&&!g.W(a,1024);g.DC(this.u,a);g.DC(this.A,a)};
g.h.KF=function(a){var b=this.player.getVideoData();b.Pd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),n3(this,b.Pd,a))};
g.h.unload=function(){g.jQ(this.player.app,"annotations_module",void 0);g.Hb(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,X1(this.player));this.M=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.UO.prototype.unload.call(this);g.AC(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.eK=function(a,b,c){this.C=null;!p3(this,b,a)&&(a=g.jp(c)&&c.responseXML?c.responseXML:null)&&(q3(this,a),g.K(g.HK(this.player),"iv-module-loaded"))};
g.h.Pz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?bpa(this):this.load())};
g.h.Ck=function(){return!!this.o&&this.o.isAvailable()};
g.h.Gx=function(){this.Ck();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ck();this.o&&(a?c?U2(this.o,c,b):U2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):V2(this.o))};
g.h.ur=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.P().F.unsubscribe("vast_info_card_add",this.Pz,this);g.fn(g.HK(this.player),"ytp-iv-drawer-open");for(var a=this.J,b=0,c=a.length;b<c;b++)g.Mo(a[b]);this.J.length=0;g.UO.prototype.X.call(this)};g.iP.annotations_module=k3;g.iP.creatorendscreen=m2;})(_yt_player);
